# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vercelgate < Formula
  desc ""
  homepage "https://github.com/khanakia/vercelgate"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Darwin_x86_64.tar.gz"
      sha256 "f0e8169e023b7c7e0066fc1903c42c3f82e370c9d576304d4e88b898efb81db4"

      def install
        bin.install "vercelgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Darwin_arm64.tar.gz"
      sha256 "e52dbdd57eb7637827626285cf5e2b90394a8c2f71d538bfb14c310721a0d7ab"

      def install
        bin.install "vercelgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Linux_x86_64.tar.gz"
        sha256 "c3a4b14286495d6ba84aabac751e0e53de7a09b4f992a10ebe7d48a9d4519dba"

        def install
          bin.install "vercelgate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Linux_arm64.tar.gz"
        sha256 "db95de53c8f050a3dda15542512ca50d8bcdfe0f4611c21247a416303a1f6b78"

        def install
          bin.install "vercelgate"
        end
      end
    end
  end
end
