# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vercelgate < Formula
  desc ""
  homepage "https://github.com/khanakia/vercelgate"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Darwin_x86_64.tar.gz"
      sha256 "d3b2719146bb6210092707e26c7c07081d298e088f220671faea710786031b4b"

      def install
        bin.install "vercelgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Darwin_arm64.tar.gz"
      sha256 "59d1a9b2ab8ce2c1aabfa0f5f2985810cea33796b228df9002fb0a6e9ee8b94d"

      def install
        bin.install "vercelgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Linux_x86_64.tar.gz"
        sha256 "f16a2a316ce4dc9a645fb350b82daf69bf231cfe8480118e3f37994f9937b860"

        def install
          bin.install "vercelgate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Linux_arm64.tar.gz"
        sha256 "dc24de48d85b93063782dcf18367cc985690b289435aa7e90b30bebd4d7758d1"

        def install
          bin.install "vercelgate"
        end
      end
    end
  end
end
