# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vercelgate < Formula
  desc ""
  homepage "https://github.com/khanakia/vercelgate"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Darwin_x86_64.tar.gz"
      sha256 "cad3cfa1a15bdbbc97ba41899e9bd8023f81d43d9922791b45623898c674fd8f"

      def install
        bin.install "vercelgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Darwin_arm64.tar.gz"
      sha256 "3045f6a25f2972ace8d5abc779cfa4156225d6a8fd0b0f03885beb93c64e4fba"

      def install
        bin.install "vercelgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Linux_x86_64.tar.gz"
        sha256 "959126aeaa3c3e507e796340d9082dcb31d869838063772f8b27a0b9c45e9d1a"

        def install
          bin.install "vercelgate"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khanakia/vercelgate/releases/download/v0.0.1/vercelgate_Linux_arm64.tar.gz"
        sha256 "a07b21351fbd222366c125e655ee5d265b763bf52525a4f96bf912c3f665c0ce"

        def install
          bin.install "vercelgate"
        end
      end
    end
  end
end
